In [151]:
import pandas as pd
import numpy as np

In [152]:
data = pd.read_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Raw data\healthdata.xlsx')

In [153]:
data.shape

(20100, 30)

In [154]:
data.head()

,Patient_ID,Policy_Number,Claim_ID,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_City,...,Discharge_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles,Claim_Submitted_Late,Is_Fraudulent
0,67349080,XAI956194550,18874,2021-06-16,2021-05-01,2024-11-20,462337.48,28,Female,Houston,...,Rehab/Skilled Nursing,47,Inpatient,3440.06,824.59,0,16,939.08,True,False
1,85973291,XAI215993963,8762,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,Other,Washington,...,Deceased,0,Outpatient,3618.40,851.43,0,6,170.40,False,True
2,62454860,XAI146653263,1920,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,Female,Seattle,...,Deceased,0,Pharmacy,2442.41,616.23,0,2,549.38,True,False
3,58632240,XAI216596381,1316,2021-11-07,2021-11-02,2025-12-24,572237.61,49,Other,Fort Worth,...,Deceased,0,Pharmacy,587.78,459.33,0,2,396.49,False,True
4,96347311,XAI056900359,17039,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,Female,New York,...,Deceased,0,Emergency Room,3047.55,847.40,0,15,865.87,True,False

In [155]:
data.columns

Index(['Patient_ID', 'Policy_Number', 'Claim_ID', 'Claim_Date', 'Service_Date',
       'Policy_Expiration_Date', 'Claim_Amount', 'Patient_Age',
       'Patient_Gender', 'Patient_City', 'Patient_State', 'Hospital_ID',
       'Provider_Type', 'Provider_Specialty', 'Provider_City',
       'Provider_State', 'Diagnosis_Code', 'Procedure_Code',
       'Number_of_Procedures', 'Admission_Type', 'Discharge_Type',
       'Length_of_Stay_Days', 'Service_Type', 'Deductible_Amount',
       'CoPay_Amount', 'Number_of_Previous_Claims_Patient',
       'Number_of_Previous_Claims_Provider', 'Provider_Patient_Distance_Miles',
       'Claim_Submitted_Late', 'Is_Fraudulent'],
      dtype='object')

In [156]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20100 entries, 0 to 20099
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Patient_ID                          20100 non-null  int64
 1   Policy_Number                       20100 non-null  object
 2   Claim_ID                            20100 non-null  int64
 3   Claim_Date                          20100 non-null  datetime64[ns]
 4   Service_Date                        20100 non-null  datetime64[ns]
 5   Policy_Expiration_Date              20100 non-null  datetime64[ns]
 6   Claim_Amount                        20100 non-null  float64
 7   Patient_Age                         20100 non-null  int64
 8   Patient_Gender                      20100 non-null  object
 9   Patient_City                        20100 non-null  object
 10  Patient_State                       20100 non-null  object
 11  Hospital_ID                         20100 non-null  int64
 12  Provider_Type                       20100 non-null  object
 13  Provider_Specialty                  20100 non-null  object
 14  Provider_City                       20100 non-null  object
 15  Provider_State                      20100 non-null  object
 16  Diagnosis_Code                      20100 non-null  object
 17  Procedure_Code                      20100 non-null  int64
 18  Number_of_Procedures                20100 non-null  int64
 19  Admission_Type                      20100 non-null  object
 20  Discharge_Type                      20100 non-null  object
 21  Length_of_Stay_Days                 20100 non-null  int64
 22  Service_Type                        20100 non-null  object
 23  Deductible_Amount                   20100 non-null  float64
 24  CoPay_Amount                        20100 non-null  float64
 25  Number_of_Previous_Claims_Patient   20100 non-null  int64
 26  Number_of_Previous_Claims_Provider  20100 non-null  int64
 27  Provider_Patient_Distance_Miles     20100 non-null  float64
 28  Claim_Submitted_Late                20100 non-null  bool
 29  Is_Fraudulent                       20100 non-null  bool
dtypes: bool(2), datetime64[ns](3), float64(4), int64(9), object(12)
memory usage: 4.3+ MB

In [157]:
data.isnull().sum()

Patient_ID                            0
Policy_Number                         0
Claim_ID                              0
Claim_Date                            0
Service_Date                          0
Policy_Expiration_Date                0
Claim_Amount                          0
Patient_Age                           0
Patient_Gender                        0
Patient_City                          0
Patient_State                         0
Hospital_ID                           0
Provider_Type                         0
Provider_Specialty                    0
Provider_City                         0
Provider_State                        0
Diagnosis_Code                        0
Procedure_Code                        0
Number_of_Procedures                  0
Admission_Type                        0
Discharge_Type                        0
Length_of_Stay_Days                   0
Service_Type                          0
Deductible_Amount                     0
CoPay_Amount                          0
Number_of_Previous_Claims_Patient     0
Number_of_Previous_Claims_Provider    0
Provider_Patient_Distance_Miles       0
Claim_Submitted_Late                  0
Is_Fraudulent                         0
dtype: int64

In [158]:
data.describe()

,Patient_ID,Claim_ID,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Hospital_ID,Procedure_Code,Number_of_Procedures,Length_of_Stay_Days,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles
count,2.010000e+04,20100.000000,20100,20100,20100,2.010000e+04,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000,20100.000000
mean,5.528158e+07,10005.580348,2022-10-03 08:36:10.746268672,2022-08-19 07:35:47.104477952,2025-04-08 12:46:03.940298496,1.245349e+06,45.104925,500.204179,92463.849851,5.510249,4.975821,2508.487758,499.665796,0.000299,10.027910,499.480532
min,1.000265e+07,1.000000,2020-01-01 00:00:00,2019-10-10 00:00:00,2020-02-11 00:00:00,5.516780e+03,0.000000,1.000000,71045.000000,1.000000,0.000000,0.030000,0.020000,0.000000,0.000000,0.020000
25%,3.266819e+07,5005.750000,2021-05-24 00:00:00,2021-04-08 00:00:00,2023-10-07 00:00:00,6.674103e+05,22.000000,251.000000,93040.000000,3.000000,0.000000,1251.440000,248.800000,0.000000,5.000000,246.380000
50%,5.551009e+07,10008.500000,2022-10-02 00:00:00,2022-08-18 00:00:00,2025-04-12 00:00:00,1.221707e+06,45.000000,500.000000,93571.000000,6.000000,0.000000,2508.875000,499.950000,0.000000,10.000000,498.410000
75%,7.814105e+07,15011.250000,2024-02-12 00:00:00,2023-12-27 00:00:00,2026-10-15 00:00:00,1.835603e+06,68.000000,752.000000,99204.000000,8.000000,0.000000,3755.080000,750.040000,0.000000,15.000000,751.000000
max,9.998440e+07,20000.000000,2025-07-11 00:00:00,2025-07-10 00:00:00,2030-06-23 00:00:00,2.499689e+06,90.000000,1000.000000,99284.000000,10.000000,60.000000,4999.870000,999.880000,1.000000,34.000000,999.980000
std,2.606038e+07,5774.135663,NaN,NaN,NaN,6.983001e+05,26.300942,288.437500,8151.470654,2.882847,13.239804,1443.579069,288.397727,0.017275,6.622332,289.745360

In [159]:
corr_matrix = data.corr(numeric_only=True)

print(corr_matrix)

                                    Patient_ID  Claim_ID  Claim_Amount  \
Patient_ID                            1.000000 -0.004845     -0.004281
Claim_ID                             -0.004845  1.000000      0.004488
Claim_Amount                         -0.004281  0.004488      1.000000
Patient_Age                           0.015068  0.000722      0.001708
Hospital_ID                          -0.003869  0.017289      0.007731
Procedure_Code                        0.003774  0.012212      0.016790
Number_of_Procedures                 -0.000868 -0.001387     -0.061722
Length_of_Stay_Days                  -0.000917  0.003060      0.016990
Deductible_Amount                    -0.001179  0.008390      0.009833
CoPay_Amount                          0.005954  0.004457     -0.002607
Number_of_Previous_Claims_Patient     0.003994 -0.001327      0.001211
Number_of_Previous_Claims_Provider   -0.013226  0.871678     -0.000577
Provider_Patient_Distance_Miles       0.000216  0.002636      0.010726
Claim_Submitted_Late                 -0.004610  0.004105     -0.005524
Is_Fraudulent                         0.009713 -0.006324      0.044919

                                    Patient_Age  Hospital_ID  Procedure_Code  \
Patient_ID                             0.015068    -0.003869        0.003774
Claim_ID                               0.000722     0.017289        0.012212
Claim_Amount                           0.001708     0.007731        0.016790
Patient_Age                            1.000000     0.006909        0.006437
Hospital_ID                            0.006909     1.000000       -0.005116
Procedure_Code                         0.006437    -0.005116        1.000000
Number_of_Procedures                   0.006989     0.004663       -0.035347
Length_of_Stay_Days                   -0.013438    -0.012400       -0.014077
Deductible_Amount                     -0.000770     0.009776       -0.000968
CoPay_Amount                           0.002008    -0.015970       -0.003370
Number_of_Previous_Claims_Patient      0.008472     0.004521        0.001406
Number_of_Previous_Claims_Provider    -0.003455     0.001971        0.007268
Provider_Patient_Distance_Miles        0.007546     0.008446       -0.001622
Claim_Submitted_Late                   0.004205     0.002105       -0.007783
Is_Fraudulent                         -0.004936     0.007414        0.035448

                                    Number_of_Procedures  Length_of_Stay_Days  \
Patient_ID                                     -0.000868            -0.000917
Claim_ID                                       -0.001387             0.003060
Claim_Amount                                   -0.061722             0.016990
Patient_Age                                     0.006989            -0.013438
Hospital_ID                                     0.004663            -0.012400
Procedure_Code                                 -0.035347            -0.014077
Number_of_Procedures                            1.000000            -0.010301
Length_of_Stay_Days                            -0.010301             1.000000
Deductible_Amount                               0.005160            -0.008690
CoPay_Amount                                   -0.004129            -0.003466
Number_of_Previous_Claims_Patient              -0.004058            -0.001056
Number_of_Previous_Claims_Provider             -0.001945             0.005226
Provider_Patient_Distance_Miles                -0.007043            -0.004176
Claim_Submitted_Late                            0.011694             0.008441
Is_Fraudulent                                   0.177968            -0.089885

                                    Deductible_Amount  CoPay_Amount  \
Patient_ID                                  -0.001179      0.005954
Claim_ID                                     0.008390      0.004457
Claim_Amount                                 0.009833     -0.002607
Patient_Age                                 -0.000770      0.002008
Hospital_ID                                  0.009776     -0.015970
Procedure_Code                              -0.000968     -0.003370
Number_of_Procedures                         0.005160     -0.004129
Length_of_Stay_Days                         -0.008690     -0.003466
Deductible_Amount                            1.000000      0.003201
CoPay_Amount                                 0.003201      1.000000
Number_of_Previous_Claims_Patient            0.001906     -0.009988
Number_of_Previous_Claims_Provider           0.006055      0.001273
Provider_Patient_Distance_Miles              0.000274      0.004932
Claim_Submitted_Late                        -0.000610     -0.011608
Is_Fraudulent                                0.006620      0.004723

                                    Number_of_Previous_Claims_Patient  \
Patient_ID                                                   0.003994
Claim_ID                                                    -0.001327
Claim_Amount                                                 0.001211
Patient_Age                                                  0.008472
Hospital_ID                                                  0.004521
Procedure_Code                                               0.001406
Number_of_Procedures                                        -0.004058
Length_of_Stay_Days                                         -0.001056
Deductible_Amount                                            0.001906
CoPay_Amount                                                -0.009988
Number_of_Previous_Claims_Patient                            1.000000
Number_of_Previous_Claims_Provider                           0.003841
Provider_Patient_Distance_Miles                              0.011863
Claim_Submitted_Late                                         0.012485
Is_Fraudulent                                               -0.009958

                                    Number_of_Previous_Claims_Provider  \
Patient_ID                                                   -0.013226
Claim_ID                                                      0.871678
Claim_Amount                                                 -0.000577
Patient_Age                                                  -0.003455
Hospital_ID                                                   0.001971
Procedure_Code                                                0.007268
Number_of_Procedures                                         -0.001945
Length_of_Stay_Days                                           0.005226
Deductible_Amount                                             0.006055
CoPay_Amount                                                  0.001273
Number_of_Previous_Claims_Patient                             0.003841
Number_of_Previous_Claims_Provider                            1.000000
Provider_Patient_Distance_Miles                               0.002788
Claim_Submitted_Late                                          0.004280
Is_Fraudulent                                                -0.007673

                                    Provider_Patient_Distance_Miles  \
Patient_ID                                                 0.000216
Claim_ID                                                   0.002636
Claim_Amount                                               0.010726
Patient_Age                                                0.007546
Hospital_ID                                                0.008446
Procedure_Code                                            -0.001622
Number_of_Procedures                                      -0.007043
Length_of_Stay_Days                                       -0.004176
Deductible_Amount                                          0.000274
CoPay_Amount                                               0.004932
Number_of_Previous_Claims_Patient                          0.011863
Number_of_Previous_Claims_Provider                         0.002788
Provider_Patient_Distance_Miles                            1.000000
Claim_Submitted_Late                                      -0.003850
Is_Fraudulent                                              0.130696

                                    Claim_Submitted_Late  Is_Fraudulent
Patient_ID                                     -0.004610       0.009713
Claim_ID                                        0.004105      -0.006324
Claim_Amount                                   -0.005524       0.044919
Patient_Age                                     0.004205      -0.004936
Hospital_ID                                     0.002105       0.007414
Procedure_Code                                 -0.007783       0.035448
Number_of_Procedures                            0.011694       0.177968
Length_of_Stay_Days                             0.008441      -0.089885
Deductible_Amount                              -0.000610       0.006620
CoPay_Amount                                   -0.011608       0.004723
Number_of_Previous_Claims_Patient               0.012485      -0.009958
Number_of_Previous_Claims_Provider              0.004280      -0.007673
Provider_Patient_Distance_Miles                -0.003850       0.130696
Claim_Submitted_Late                            1.000000       0.015432
Is_Fraudulent                                   0.015432       1.000000

In [160]:
drop_columns = [
    'Patient_ID',
    'Policy_Number',
    'Claim_ID',
    'Hospital_ID',
    'Diagnosis_Code',
    'Procedure_Code',
    'Patient_City',
    'Provider_City'
]
data.drop(columns=drop_columns, inplace=True)

In [161]:
data

,Claim_Date,Service_Date,Policy_Expiration_Date,Claim_Amount,Patient_Age,Patient_Gender,Patient_State,Provider_Type,Provider_Specialty,Provider_State,...,Discharge_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,CoPay_Amount,Number_of_Previous_Claims_Patient,Number_of_Previous_Claims_Provider,Provider_Patient_Distance_Miles,Claim_Submitted_Late,Is_Fraudulent
0,2021-06-16,2021-05-01,2024-11-20,462337.48,28,Female,WI,Clinic,Cardiology,WA,...,Rehab/Skilled Nursing,47,Inpatient,3440.06,824.59,0,16,939.08,True,False
1,2025-01-19,2025-01-17,2029-04-07,1883481.30,40,Other,CO,Laboratory,Cardiology,AZ,...,Deceased,0,Outpatient,3618.40,851.43,0,6,170.40,False,True
2,2023-05-05,2023-03-24,2024-09-04,1500658.89,90,Female,FL,Hospital,Neurology,NC,...,Deceased,0,Pharmacy,2442.41,616.23,0,2,549.38,True,False
3,2021-11-07,2021-11-02,2025-12-24,572237.61,49,Other,MD,Specialist Office,Pediatrics,TX,...,Deceased,0,Pharmacy,587.78,459.33,0,2,396.49,False,True
4,2024-03-25,2024-02-18,2028-07-30,2088293.84,24,Female,FL,Specialist Office,Pediatrics,PA,...,Deceased,0,Emergency Room,3047.55,847.40,0,15,865.87,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20095,2024-03-12,2024-02-25,2025-11-05,1182670.52,9,Male,FL,Specialist Office,Cardiology,IL,...,Rehab/Skilled Nursing,0,Emergency Room,3961.31,973.40,0,5,441.98,False,True
20096,2024-10-19,2024-09-07,2029-09-20,1225019.60,60,Other,MA,Specialist Office,Oncology,NY,...,Against Medical Advice,58,Inpatient,3383.95,998.72,0,0,602.85,True,False
20097,2022-04-05,2022-02-28,2026-03-23,1320858.11,15,Other,DC,Specialist Office,Cardiology,CO,...,Home,0,Outpatient,18.69,713.95,0,5,585.15,True,True
20098,2024-10-04,2024-09-26,2028-11-03,484552.40,41,Other,IL,Laboratory,Psychiatry,MI,...,Transfer to another facility,0,Emergency Room,3165.91,761.46,0,11,338.57,False,False
20099,2024-09-30,2024-08-04,2025-07-28,166117.59,57,Female,CO,Pharmacy,Cardiology,GA,...,Home,0,Laboratory,4177.15,769.07,0,13,931.32,True,False

In [162]:
data['Is_Fraudulent'].value_counts()

Is_Fraudulent
False    15089
True      5011
Name: count, dtype: int64

In [163]:
numerical_columns = data.select_dtypes(include=['int64', 'float64']).columns

print(numerical_columns)

Index(['Claim_Amount', 'Patient_Age', 'Number_of_Procedures',
       'Length_of_Stay_Days', 'Deductible_Amount', 'CoPay_Amount',
       'Number_of_Previous_Claims_Patient',
       'Number_of_Previous_Claims_Provider',
       'Provider_Patient_Distance_Miles'],
      dtype='object')

In [164]:
for col in numerical_columns:

    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[col] < lower_bound) |
        (data[col] > upper_bound)
    ]

    print(f"{col}")
    print(f"Number of outliers: {len(outliers)}")
    print("-" * 50)

Claim_Amount
Number of outliers: 0
--------------------------------------------------
Patient_Age
Number of outliers: 0
--------------------------------------------------
Number_of_Procedures
Number of outliers: 0
--------------------------------------------------
Length_of_Stay_Days
Number of outliers: 3287
--------------------------------------------------
Deductible_Amount
Number of outliers: 0
--------------------------------------------------
CoPay_Amount
Number of outliers: 0
--------------------------------------------------
Number_of_Previous_Claims_Patient
Number of outliers: 6
--------------------------------------------------
Number_of_Previous_Claims_Provider
Number of outliers: 23
--------------------------------------------------
Provider_Patient_Distance_Miles
Number of outliers: 0
--------------------------------------------------

In [165]:
Q1 = data['Length_of_Stay_Days'].quantile(0.25)
Q3 = data['Length_of_Stay_Days'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

data['Length_of_Stay_Days'] = data['Length_of_Stay_Days'].clip(lower, upper)

In [166]:
data.to_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Clean data\clean_data.xlsx', index=False)