In [24]:
import pandas as pd
import numpy as np

In [25]:
data=pd.read_excel(r'D:\1.Tekworks\Project\Healthcare Insurance Claim\Backend\1.Dataset\Encoder data\Encoded_data.xlsx')

In [26]:
data.head()

,Claim_Amount,Patient_Age,Patient_Gender,Patient_State,Provider_State,Number_of_Procedures,Admission_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,462337.48,28,0,19,18,2,0,0,2,3440.06,...,0,0,0,0,0,1,0,2021,6,46
1,1883481.30,40,2,2,0,2,0,0,4,3618.40,...,0,0,0,1,0,0,0,2025,1,2
2,1500658.89,90,0,4,12,1,4,0,5,2442.41,...,0,0,0,1,0,0,0,2023,5,42
3,572237.61,49,2,9,16,4,3,0,5,587.78,...,0,0,0,1,0,0,0,2021,11,5
4,2088293.84,24,0,4,15,5,1,0,1,3047.55,...,0,0,0,1,0,0,0,2024,3,36

In [27]:
scale_columns = [
    'Claim_Amount',
    'Patient_Age',
    'Number_of_Procedures',
    'Length_of_Stay_Days',
    'Deductible_Amount',
    'CoPay_Amount',
    'Number_of_Previous_Claims_Patient',
    'Number_of_Previous_Claims_Provider',
    'Provider_Patient_Distance_Miles',
    'Claim_Year',
    'Claim_Month',
    'Claim_Delay_Days'
]

In [28]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

data[scale_columns] = scaler.fit_transform(data[scale_columns])

In [29]:
print(data.columns.tolist())

['Claim_Amount', 'Patient_Age', 'Patient_Gender', 'Patient_State', 'Provider_State', 'Number_of_Procedures', 'Admission_Type', 'Length_of_Stay_Days', 'Service_Type', 'Deductible_Amount', 'CoPay_Amount', 'Number_of_Previous_Claims_Patient', 'Number_of_Previous_Claims_Provider', 'Provider_Patient_Distance_Miles', 'Claim_Submitted_Late', 'Is_Fraudulent', 'Provider_Type_Hospital', 'Provider_Type_Laboratory', 'Provider_Type_Pharmacy', 'Provider_Type_Specialist Office', 'Provider_Type_Urgent Care', 'Provider_Specialty_Dermatology', 'Provider_Specialty_General Practice', 'Provider_Specialty_Neurology', 'Provider_Specialty_Oncology', 'Provider_Specialty_Orthopedics', 'Provider_Specialty_Pediatrics', 'Provider_Specialty_Physical Therapy', 'Provider_Specialty_Psychiatry', 'Provider_Specialty_Radiology', 'Discharge_Type_Deceased', 'Discharge_Type_Home', 'Discharge_Type_Rehab/Skilled Nursing', 'Discharge_Type_Transfer to another facility', 'Claim_Year', 'Claim_Month', 'Claim_Delay_Days']

In [30]:
data.head()

,Claim_Amount,Patient_Age,Patient_Gender,Patient_State,Provider_State,Number_of_Procedures,Admission_Type,Length_of_Stay_Days,Service_Type,Deductible_Amount,...,Provider_Specialty_Physical Therapy,Provider_Specialty_Psychiatry,Provider_Specialty_Radiology,Discharge_Type_Deceased,Discharge_Type_Home,Discharge_Type_Rehab/Skilled Nursing,Discharge_Type_Transfer to another facility,Claim_Year,Claim_Month,Claim_Delay_Days
0,-1.121339,-0.650370,0,19,18,-1.217663,0,0.0,2,0.645337,...,0,0,0,0,0,1,0,-0.796174,-0.086455,0.036400
1,0.913860,-0.194101,2,2,0,-1.217663,0,0.0,4,0.768881,...,0,0,0,1,0,0,0,1.702260,-1.550441,-1.635309
2,0.365625,1.707018,0,4,12,-1.564551,4,0.0,5,-0.045775,...,0,0,0,1,0,0,0,0.453043,-0.379252,-0.115574
3,-0.963953,0.148100,2,9,16,-0.523887,3,0.0,5,-1.330551,...,0,0,0,1,0,0,0,-0.796174,1.377530,-1.521329
4,1.207168,-0.802460,0,4,15,-0.176999,1,0.0,1,0.373430,...,0,0,0,1,0,0,0,1.077652,-0.964847,-0.343534

In [31]:
import pickle

pickle.dump(
    scaler,
    open("scaler.pkl", "wb")
)

In [32]:
data.to_excel(r'D:\1.Tekworks\Project\Tekwork-Project\backend\6.Artifacts\Scaling_data.xlsx', index=False)